/* auto-generated by napi-rs */
'use strict'

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  if (!existsSync('/usr/bin/ldd')) return true
  return readFileSync('/usr/bin/ldd', 'utf8').includes('musl')
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64': nativeBinding = require('@deepstrike/core-android-arm64'); break
      case 'arm': nativeBinding = require('@deepstrike/core-android-arm-eabi'); break
      default: throw new Error(`Unsupported architecture on Android: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64': nativeBinding = require('@deepstrike/core-win32-x64-msvc'); break
      case 'ia32': nativeBinding = require('@deepstrike/core-win32-ia32-msvc'); break
      case 'arm64': nativeBinding = require('@deepstrike/core-win32-arm64-msvc'); break
      default: throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'deepstrike-core.darwin-universal.node'))
    try {
      if (localFileExisted) { nativeBinding = require('./deepstrike-core.darwin-universal.node'); break }
    } catch {}
    switch (arch) {
      case 'x64': nativeBinding = require('@deepstrike/core-darwin-x64'); break
      case 'arm64': nativeBinding = require('@deepstrike/core-darwin-arm64'); break
      default: throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    nativeBinding = require('@deepstrike/core-freebsd-x64')
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        nativeBinding = isMusl()
          ? require('@deepstrike/core-linux-x64-musl')
          : require('@deepstrike/core-linux-x64-gnu')
        break
      case 'arm64':
        nativeBinding = isMusl()
          ? require('@deepstrike/core-linux-arm64-musl')
          : require('@deepstrike/core-linux-arm64-gnu')
        break
      case 'arm':
        nativeBinding = require('@deepstrike/core-linux-arm-gnueabihf')
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

module.exports = nativeBinding
