from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("deepstrike")
except PackageNotFoundError:
    __version__ = "0+unknown"

from deepstrike._kernel import (
    Message, ToolCall, ToolResult, ToolSchema,
    SkillMetadata,
)
from deepstrike.runtime import (
    RuntimeRunner,
    RuntimeOptions,
    ResourceQuota,
    MemoryPolicy,
    MemoryWriteRateLimit,
    SchedulerBudget,
    SubAgentHarnessConfig,
    builtin_reducers,
    resolve_reducer,
    FileWorkflowStore,
    WorktreeExecutionPlane,
    GitWorktreeManager,
    loop_instruction,
    classify_instruction,
    judge_goal,
    extract_loop_continue,
    extract_classify_branch,
    extract_judge_winner,
    OsProfile,
    assert_native_profile,
    os_profile,
    collect_text,
    LocalExecutionPlane,
    InMemorySessionLog,
    FileSessionLog,
    SessionLog,
    ProviderReplay,
    FilteredExecutionPlane,
    SubAgentOrchestrator,
    spawn_standalone,
    default_sub_agent_orchestrator,
    DEFAULT_SANDBOX_POLICY,
    validate_declarative_policy,
    ReplayProvider,
    ReplayProviderOpts,
    extract_recorded_messages,
    Criterion,
    Verdict,
    VerdictDetail,
    judge,
    build_eval_messages,
    parse_verdict,
    verdict_output_schema,
)
from deepstrike.governance import Governance, GovernanceVerdict
from deepstrike.providers import (
    LLMProvider, RenderedContext, ProviderRunState, RuntimePolicy,
    AnthropicProvider, OpenAIProvider, OpenAIResponsesProvider,
    QwenProvider, DeepSeekProvider, MiniMaxAnthropicProvider, MiniMaxOpenAIProvider, OllamaProvider, KimiProvider,
    StreamEvent, TextDelta, ThinkingDelta,
    ToolCallEvent, ToolDeltaEvent, ToolSuspendEvent, ToolResultEvent, DoneEvent, ErrorEvent,
    PermissionRequestEvent, PermissionResolvedEvent, PermissionResponse, ToolArgumentRepairedEvent,
    RetryConfig, CircuitBreaker, TokenUsage, ProviderToolSpec,
)
from deepstrike.tools import RegisteredTool, tool, streaming_tool, validate_tool_arguments, execute_tools, read_file
from deepstrike.memory import (
    WorkingMemory,
    DreamStore, DreamResult, SessionData, MemoryEntry, CurationResult, CurationStats,
    InMemoryDreamStore,
)
from deepstrike.safety import PermissionManager, PermissionMode, Permission, PermissionDecision
from deepstrike.harness import (
    QualityGate,
    SinglePassHarness, HarnessLoop, EvalLoopHarness,
    HarnessRequest, HarnessOutcome,
    # I3.1: surface harness types so hosts can construct verdicts and stream-event handlers
    # without importing from deepstrike.harness.harness directly.
    HarnessEvent, CriterionResult,
)
from deepstrike.skills import SkillRegistry
from deepstrike.knowledge import KnowledgeSource
from deepstrike.signals import RuntimeSignal, SignalSource, ScheduledPrompt, SignalGateway
from deepstrike.types.agent import (
    AgentIdentity, AgentCapabilityFilter, AgentRunSpec,
    AgentProcessChangedObservation, SubAgentResult, LoopResult,
    KernelAgentRole, AgentIsolation, ContextInheritance,
    MilestoneContract, MilestonePhase, MilestoneCheckResult, MilestonePolicy,
    milestone_check_pass, milestone_check_fail,
    WorkflowSpec, WorkflowNodeSpec, WorkflowSpawnInfo, workflow_spec_to_kernel,
    workflow_node_spec_to_kernel, submit_workflow_nodes_to_kernel, submit_workflow_to_kernel, submit_workflow_nodes_tool, start_workflow_tool,
    workflow_budget_note,
    fanout_synthesize, generate_and_filter, verify_rules, gen_eval,
)
from deepstrike.collaboration import (
    AcceptanceCriterion, VerificationContract, ContractCheckResult,
    ContractBuilder, format_contract_for_system_prompt, contract_to_criteria_strings,
    AgentPool, AgentRole, IsolatedVerifierContext,
    ContractDrivenHarness, ContractOutcome, ContractHarnessOptions, Violation,
    HandoffArtifact, HandoffBus, ContractOutcomeInput,
    CreatorVerifierMode, OrchestrationMode, CreatorVerifierMetrics,
)
__all__ = [
    "RuntimeRunner",
    "RuntimeOptions",
    "builtin_reducers",
    "resolve_reducer",
    "FileWorkflowStore",
    "WorktreeExecutionPlane",
    "GitWorktreeManager",
    "loop_instruction",
    "classify_instruction",
    "judge_goal",
    "extract_loop_continue",
    "extract_classify_branch",
    "extract_judge_winner",
    "ResourceQuota",
    "MemoryPolicy",
    "MemoryWriteRateLimit",
    "SchedulerBudget",
    "SubAgentHarnessConfig",
    "OsProfile",
    "assert_native_profile",
    "os_profile",
    "collect_text",
    "LocalExecutionPlane",
    "InMemorySessionLog",
    "FileSessionLog",
    "SessionLog",
    "ProviderReplay",
    "ProviderReplay",
    "ProviderReplay",
    "LLMProvider", "RenderedContext", "ProviderRunState", "RuntimePolicy", "AnthropicProvider", "OpenAIProvider",
    "OpenAIResponsesProvider",
    "QwenProvider", "DeepSeekProvider", "MiniMaxAnthropicProvider", "MiniMaxOpenAIProvider", "OllamaProvider", "KimiProvider",
    "StreamEvent", "TextDelta", "ThinkingDelta",
    "ToolCallEvent", "ToolDeltaEvent", "ToolSuspendEvent", "ToolResultEvent", "DoneEvent", "ErrorEvent",
    "PermissionRequestEvent", "PermissionResolvedEvent", "PermissionResponse", "ToolArgumentRepairedEvent",
    "RetryConfig", "CircuitBreaker", "TokenUsage", "ProviderToolSpec",
    "RegisteredTool", "tool", "streaming_tool", "validate_tool_arguments", "execute_tools", "read_file",
    "WorkingMemory",
    "DreamStore", "DreamResult", "SessionData", "MemoryEntry", "CurationResult", "CurationStats",
    "PermissionManager", "PermissionMode", "Permission", "PermissionDecision",
    "QualityGate",
    "SinglePassHarness", "HarnessLoop", "EvalLoopHarness", "HarnessRequest", "HarnessOutcome",
    "HarnessEvent", "CriterionResult",
    "SkillRegistry",
    "KnowledgeSource",
    "RuntimeSignal", "SignalSource", "ScheduledPrompt", "SignalGateway",
    "Message", "ToolCall", "ToolResult", "ToolSchema",
    "SkillMetadata",
    "Governance", "GovernanceVerdict",
    # Sub-agent isolation
    "AgentIdentity", "AgentCapabilityFilter", "AgentRunSpec",
    "AgentProcessChangedObservation", "SubAgentResult", "LoopResult",
    "KernelAgentRole", "AgentIsolation", "ContextInheritance",
    "MilestoneContract", "MilestonePhase", "MilestoneCheckResult", "MilestonePolicy",
    "milestone_check_pass", "milestone_check_fail",
    "FilteredExecutionPlane",
    "SubAgentOrchestrator", "spawn_standalone", "default_sub_agent_orchestrator",
    "DEFAULT_SANDBOX_POLICY", "validate_declarative_policy",
    # Collaboration layer
    "AcceptanceCriterion", "VerificationContract", "ContractCheckResult",
    "ContractBuilder", "format_contract_for_system_prompt", "contract_to_criteria_strings",
    "AgentPool", "AgentRole", "IsolatedVerifierContext",
    "ContractDrivenHarness", "ContractOutcome", "ContractHarnessOptions", "Violation",
    "HandoffArtifact", "HandoffBus", "ContractOutcomeInput",
    "CreatorVerifierMode", "OrchestrationMode", "CreatorVerifierMetrics",
    # Workflow DAG drive (W0-ABI)
    "WorkflowSpec", "WorkflowNodeSpec", "WorkflowSpawnInfo", "workflow_spec_to_kernel",
    "workflow_node_spec_to_kernel", "submit_workflow_nodes_to_kernel", "submit_workflow_to_kernel", "submit_workflow_nodes_tool", "start_workflow_tool",
    "workflow_budget_note",
    "fanout_synthesize", "generate_and_filter", "verify_rules", "gen_eval",
    "__version__",
]
